# Generated by Django 3.2.16 on 2022-10-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('UID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('REQ', 'Required'), ('CHO', 'Choice'), ('FRE', 'Free')], default='REQ', max_length=3)),
                ('description', models.TextField()),
                ('credits', models.PositiveIntegerField(default=4)),
                ('student_limit', models.PositiveIntegerField(default=9999)),
                ('language', models.CharField(choices=[('ENG', 'English'), ('CZE', 'Czech'), ('GER', 'German')], default='CZE', max_length=3)),
            ],
        ),
    ]
