# Generated by Django 3.2.16 on 2022-10-25 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WIS2_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomUID', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIS2_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIS2_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('ID', models.UUIDField(primary_key=True, serialize=False)),
                ('max_points', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=2000)),
                ('kind', models.CharField(choices=[('PER', 'Periodic'), ('ONE', 'OneTime')], default='ONE', max_length=3)),
                ('CourseUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIS2_app.course')),
                ('RoomUID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WIS2_app.room')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TerminPeriod',
            fields=[
                ('TerminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='WIS2_app.termin')),
                ('start', models.DateTimeField()),
                ('repeats', models.PositiveIntegerField()),
                ('periodicity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TerminSingle',
            fields=[
                ('TerminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='WIS2_app.termin')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Termin2Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_given', models.PositiveIntegerField()),
                ('StudentUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIS2_app.student')),
                ('TeacherUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIS2_app.teacher')),
                ('TerminUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIS2_app.termin')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='UserUID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIS2_app.user'),
        ),
        migrations.AddField(
            model_name='student',
            name='UserUID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIS2_app.user'),
        ),
        migrations.CreateModel(
            name='Garant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('CourseUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIS2_app.course')),
                ('UserUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIS2_app.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='termin2body',
            constraint=models.UniqueConstraint(fields=('UserUID', 'StudentUID', 'TeacherUID'), name='unique termin,student,teacher UID'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('UserUID', 'CourseUID'), name='unique teacher course ID'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('UserUID', 'CourseUID'), name='unique student course ID'),
        ),
        migrations.AddConstraint(
            model_name='garant',
            constraint=models.UniqueConstraint(fields=('UserUID', 'CourseUID'), name='unique garant course ID'),
        ),
    ]
