# Generated by Django 3.2.16 on 2022-10-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIS2_app', '0002_auto_20221025_1523'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='termin2body',
            constraint=models.UniqueConstraint(fields=('TerminUID', 'StudentUID', 'TeacherUID'), name='unique termin,student,teacher UID'),
        ),
    ]
