# Generated by Django 3.2.16 on 2022-10-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WIS2_app', '0003_auto_20221025_1524'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='termin2body',
            name='unique termin,student,teacher UID',
        ),
    ]
