# Generated by Django 3.2.16 on 2022-11-24 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WIS2_app', '0004_remove_termin2body_unique termin,student,teacher uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='name',
            field=models.CharField(default='pulsemestralka', max_length=30),
        ),
        migrations.AddField(
            model_name='terminperiod',
            name='kind',
            field=models.CharField(choices=[('PLEC', 'Practice lecture'), ('LEC', 'Lecture')], default='LEC', max_length=5),
        ),
        migrations.AddField(
            model_name='terminsingle',
            name='kind',
            field=models.CharField(choices=[('EXM', 'Exam'), ('PRJ', 'Project')], default='EXM', max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='garant',
            name='UserUID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='UserUID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='UserUID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='termin',
            name='ID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='terminperiod',
            name='TerminID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='WIS2_app.termin'),
        ),
        migrations.AlterField(
            model_name='terminsingle',
            name='TerminID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='WIS2_app.termin'),
        ),
        migrations.AddConstraint(
            model_name='termin2body',
            constraint=models.UniqueConstraint(fields=('TerminUID', 'StudentUID', 'TeacherUID'), name='unique termin,student,teacher UID'),
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
